name: Build and Deploy Server

on:
  push:
    paths: [ "backend/**" ]
    branches: [ "main" ]
  pull_request:
    paths: [ "backend/**" ]
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17.0.6'
          distribution: 'temurin'
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/riftstats-backend:latest

  deploy:
    name: Deploy Server
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 and Restart Container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/riftstats-backend:latest
            docker stop riftstats-backend || true
            docker rm -f riftstats-backend || true
            docker run -d \
              --name riftstats-backend \
              --restart unless-stopped \
              -e SPRING_DATASOURCE_URL="${{ secrets.DATABASE_URL }}" \
              -e SPRING_DATASOURCE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
              -e SPRING_DATASOURCE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/riftstats-backend:latest
